// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnp1aW1bu3otJsNgpXmTZSj3_H0I0MR4Q',
    appId: '1:752943739137:web:4bd3f837dfda45ab74ab00',
    messagingSenderId: '752943739137',
    projectId: 'game-track-ede21',
    authDomain: 'game-track-ede21.firebaseapp.com',
    storageBucket: 'game-track-ede21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wy-O7zEYgxcQfbC29GJ_AJl4zTy1-dA',
    appId: '1:752943739137:android:11029ccb69ab64c674ab00',
    messagingSenderId: '752943739137',
    projectId: 'game-track-ede21',
    storageBucket: 'game-track-ede21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyaK2S8ftdURaewqZmLo1Nf-ppXnuodsQ',
    appId: '1:752943739137:ios:55bda6cc67b380e674ab00',
    messagingSenderId: '752943739137',
    projectId: 'game-track-ede21',
    storageBucket: 'game-track-ede21.firebasestorage.app',
    iosBundleId: 'com.gametrack.gametrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyaK2S8ftdURaewqZmLo1Nf-ppXnuodsQ',
    appId: '1:752943739137:ios:55bda6cc67b380e674ab00',
    messagingSenderId: '752943739137',
    projectId: 'game-track-ede21',
    storageBucket: 'game-track-ede21.firebasestorage.app',
    iosBundleId: 'com.gametrack.gametrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnp1aW1bu3otJsNgpXmTZSj3_H0I0MR4Q',
    appId: '1:752943739137:web:63f19b432b3642ab74ab00',
    messagingSenderId: '752943739137',
    projectId: 'game-track-ede21',
    authDomain: 'game-track-ede21.firebaseapp.com',
    storageBucket: 'game-track-ede21.firebasestorage.app',
  );
}
